### Create a question
POST http://localhost:8000/questions/
Content-Type: application/json

{
  "id": 2,
  "number": 1,
  "title": "2 asfasfasfa",
  "body": "ef efis efefe ef efefef",
  "created_at": "2023-05-07T00:00:00",
  "link_to_s3_question_pic": "https://sefef3.example.com/test-question"
}

### Get a question by ID
GET http://localhost:8000/questions/1

### Get all questions
GET http://localhost:8000/questions/

### Get a random question with specific title
# Note: the title is case sensitive and should be URL encoded
GET http://localhost:8000/questions/random/?title=2%20asfasfasfa


### Update a question
PUT http://localhost:8000/questions/1
Content-Type: application/json

{
  "id": 1,
  "number": 2,
  "title": "Updated Test Question",
  "body": "This is an updated test question",
  "created_at": "2023-05-08T00:00:00",
  "link_to_s3_question_pic": "https://s3.example.com/updated-test-question"
}


### Delete a question
DELETE http://localhost:8000/questions/1
